# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Polished: Knockout
email: jared@jaredwhite.com
description: > # this means to ignore newlines until "baseurl:"
  An Opal library for creating view models that use Knockout.js for dynamic HTML DOM updates and event handling.
baseurl: "/knockout" # the subpath of your site, e.g. /blog
url: "http://polished-rb.github.io" # the base hostname & protocol for your site
twitter_username: jaredcwhite
github_username:  polished-rb

# Build settings
markdown: kramdown
